
server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:~/Users/ivanpaulrutale/DATA/Projects/Spring/spring-boot-demo/src/main/resources/h2_db
    driverClassName: org.h2.Driver
    username: rutale
    password: rutale

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        generate_statisitics: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug